import os
# print(os.getcwd())
# print(dir(os))
# os.chdir("c://")
# print(os.getcwd())
# os.mkdir("this")
# os.makedirs("this/that")
# os.rename("abhi.txt", "abhisaini.txt")
# print(os.environ.get("path"))
# print(os.listdir("c:/"))
# print(os.path.join("c:/", "abhi.txt"))
# print(os.path.exists("c://Program Files"))
# print(os.path.isfile("c://Program Files"))